### ISSUE TITLE
ConnectionError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by AnbuBlack** [PatrickAlphaC/brownie_simple_storage#42]
I got this error working with sepolia 

since brownie does not contains sepolia i add the following command 
brownie networks add Ethereum sepolia host="https://rpc.sepolia.dev" chainid=11155111 

ConnectionError: HTTPSConnectionPool(host='rpc.sepolia.dev', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020878F59AC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by abrosua** [comment]
hi any updates on this? Or do you have any alternatives?

**Comment by abrosua** [comment]
hi @AnbuBlack, I solved this by using the sepolia endpoint by Infura, first create a `network-config.yaml`:
```
live:
- name: Ethereum
  networks:
  - chainid: 11155111
    explorer: https://api-sepolia.etherscan.io/api
    host: https://sepolia.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    id: sepolia
    multicall2: '0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696'
    name: Sepolia (Infura)
```

Then you can just import the network by using this command:
```
brownie networks import ./network-config.yaml
```

And make sure you have your Infura Project ID (now it's called API key) on the project's `.env` file:
```
export WEB3_INFURA_PROJECT_ID=<your_infura_api_key_here>
```
